"""empty message

Revision ID: 1d7fc19fcf1e
Revises: 2b017edaa91f
Create Date: 2018-04-30 14:04:30.998342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7fc19fcf1e'
down_revision = '2b017edaa91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('category', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_category'), 'user', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_category'), table_name='user')
    op.drop_column('user', 'category')
    # ### end Alembic commands ###
